### ISSUE TITLE
tint module

### ISSUE THREAD

**Issue by FlorentF9** [zichuan-liu/TimeXplusplus#2]
Hi, thanks for releasing your code!

I wondered what is the module "tint" used in `bc_model.py` ?

`from tint.models import MLP, RNN`

It does not seem to be in the requirements and I could not find the corresponding package (there is a package [tint](https://python-tint.readthedocs.io/) but it is about colors, not MLPs or RNNs..)

**Comment by zichuan-liu** [comment]
Hi, thank you for your attention,
The package tint is from [time_interpret](https://github.com/josephenguehard/time_interpret) and it should be installed as `pip install time_interpret`

**Comment by zichuan-liu** [comment]
I added this package to the requirements file, where MLPs in tint are just more convenient for constructing reparameterized distributions in `DistributionParams` for $KL(P_X , P_{tilde_X})$.

Thanks again.
