### ISSUE TITLE
which version of python is used?

### ISSUE THREAD

**Issue by chowkamlee81** [zichuan-liu/TimeXplusplus#3]
using python3.10, python3.8, python3.9, unable to install packages using requirements.txt file

**Comment by flyingdoog** [comment]
I have made a request to fix these issues. 

https://github.com/zichuan-liu/TimeXplusplus/pull/6

I tested Python 3.12.6.  But I think python 3.10 3.8 or 3.9 should also work.

```shell
pip install -r requirements.txt
cd timesynth-0.2.4/
pip install .
cd ../experiments/freqshape/
python bc_model_ptype.py
```
