### ISSUE TITLE
Hard to reproduce the results

### ISSUE THREAD

**Issue by crishna0401** [zichuan-liu/TimeXplusplus#5]
It would be helpful if you could add shell scripts, make the paths and requirements updated. I tried to reproduce the results but facing a lot of issues like unable to install all requirements, paths issue.

**Comment by flyingdoog** [comment]
I have made a request to fix these issues. 

https://github.com/zichuan-liu/TimeXplusplus/pull/6

```shell
pip install -r requirements.txt
cd timesynth-0.2.4/
pip install .
cd ../experiments/freqshape/
python bc_model_ptype.py
```

**Comment by crishna0401** [comment]
@flyingdoog  Thanks, it's working.
